### ISSUE TITLE
 Error generating circuit inputs: TypeError with `genAccountCode` function in `generateCircuitInputs.ts`

### ISSUE THREAD

**Issue by AzanAdnan23** [zkemail/jwt-tx-builder#11]
I encountered an error while running the code locally. The error message is as follows:

Error generating circuit inputs: 

```
TypeError: (0 , _zk_email_relayer_utils__WEBPACK_IMPORTED_MODULE_1__.genAccountCode) is not a function
    at handler (webpack-internal:///(api)/./pages/api/generateCircuitInputs.ts:26:106)
```

The issue occurs in the **`frontend/pages/api/generateCircuitInputs.ts`** file, where the following import is made:

`import { genAccountCode } from "@zk-email/relayer-utils";`

I am able to run the demo successfully, but the error only appears when running the code locally.

**Steps to Reproduce:**
1. Clone the repo.
2. Run the code locally.
3. Try to generate circuit inputs.
4. Observe the error in the console.

**Expected Behavior:**
The circuit inputs should generate successfully without any errors.

**Actual Behavior:**
The error mentioned above occurs, and the function `getAccountCode` seems to be undefined or not properly imported.

**Comment by AzanAdnan23** [comment]
I have checked `node_modules/@zk-email/relayer-utils`, and there is no `getAccountCode`. However, there is a function exporting `generateAccountCode`, so I used that instead. Despite this, I'm still getting the error mentioned above. Is the issue with the relayer package? Should I add it to the `packages` folder and build it there?

**Comment by shreyas-londhe** [comment]
Hi @AzanAdnan23 Sorry for the late reply, you can check the `main` branch for the latest working code now.

**Comment by AzanAdnan23** [comment]
Thanks @shreyas-londhe , I will look into this.
