### ISSUE TITLE
Refactor: Separate JWTVerifier from Jwt-Tx-Builder

### ISSUE THREAD

**Issue by shreyas-londhe** [zkemail/jwt-tx-builder#5]
Need to separate the core `jwt-verifier` template from the `tx-builder` functionality.

**Comment by Divide-By-0** [comment]
sweet. this would be helpful as well since then we can composably add https://github.com/zkemail/noir-jwt as an alternate jwt proof as well

**Comment by shreyas-londhe** [comment]
That sounds good, I can coordinate with @saleel on making the API uniform so we can choose which proofs to generate.

**Comment by sanjay-sol** [comment]
Hello, I am applying for the smart contract role as part of your hiring challenge. I will be working on this issue as my submission.
