### ISSUE TITLE
JWT Prover Service Fails with Special Characters in Google Account

### ISSUE THREAD

**Issue by saugardev** [zkemail/jwt-tx-builder#8]
### Description

The JWT demo flow fails when attempting to generate a proof using a Google account containing special characters in the name. 

**Steps to Reproduce**
1. Initiate the JWT demo flow
2. Authenticate with Google account containing the name "Saúl García" (for example)
3. Attempt to generate proof

**Current Behavior**
The service returns a 500 Internal Server Error when processing the request.

**Error Details**
```json
{
  "error": "Error from JWT prover service",
  "message": "<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n",
  "status": 500
}
```

**Comment by shreyas-londhe** [comment]
@saugardev Solve this in #6. Thanks for pointing it out

**Comment by leif-runescribe** [comment]
is this still considered for the hiring task
